#!/sbin/openrc-run
# Copyright 1999-2023 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/xython-client-looper.sh"
PIDFILE="/run/xython-client.pid"
start_stop_daemon_args="--user xython:xython --background --make-pidfile --pidfile ${PIDFILE}"

depend() {
	need localmount net
	use logger
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --pidfile "${PIDFILE}"
	eend $?
}
