#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

DAEMON="/usr/bin/gunicorn"
#DAEMON_ARGS="manage  scheduler $LOGFILE $LOGLEVEL"
NAME=lava-server-gunicorn
PIDFILE=/var/run/lava-server-gunicorn.pid

depend() {
	use postgresql
}

start() {
	ebegin "Starting ${SVCNAME}"
	cd /
	/usr/bin/gunicorn -D -u lavaserver -g lavaserver --log-file /var/log/lava-server/gunicorn.log --bind '127.0.0.1:8000' --pid $PIDFILE lava_server.wsgi
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	eend $?
}
