#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	use dns
}

# Default variables
MASTER_URL="tcp://localhost:5556"
LOGGER_URL="tcp://localhost:5555"
LOGLEVEL="DEBUG"
HOSTNAME=""
IPV6=""
ENCRYPT=""
MASTER_CERT=""
SLAVE_CERT=""

NAME=lava-slave
PIDFILE=/var/run/lava-slave.pid

[ -r /etc/lava-dispatcher/$NAME ] && . /etc/lava-dispatcher/$NAME

DAEMON_ARGS="--master $MASTER_URL --socket-addr $LOGGER_URL --level $LOGLEVEL $IPV6 $ENCRYPT $MASTER_CERT $SLAVE_CERT $HOSTNAME"

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --background --pidfile $PIDFILE --name $NAME /usr/bin/lava-slave -- $DAEMON_ARGS
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	eend $?
}
