--- a/Makefile.orig	2011-06-17 14:44:47.000000000 +0200
+++ b/Makefile	2011-06-17 14:45:15.000000000 +0200
@@ -52,6 +52,6 @@
 install:
 	cp $(TARGET) $(HOME)/.xmms/Plugins/Input
 clean:
-	rm -f *.o *.so *.a .syms syms
+	rm -f *.o *.so *.a .syms syms ${SAPLIB}
 realclean: clean
 	cd saplib && make clean
