#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

DAEMON="/usr/bin/lava-server"
DAEMON_ARGS="manage lava-master $LOGFILE $LOGLEVEL"
NAME=lava-master
PIDFILE=/var/run/lava-master.pid

depend() {
	use postgresql
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	eend $?
}
