#!/sbin/openrc-run
# Copyright 1999-2023 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/munin-node-python"
PIDFILE="/run/munin-node-python.pid"
start_stop_daemon_args="--background --make-pidfile --pidfile ${PIDFILE}"
command_args="--daemon --netport 4949"

depend() {
	need localmount net
	use logger
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --pidfile "${PIDFILE}"
	eend $?
}
